### ISSUE TITLE
put sensitive credentials in a .env

### ISSUE THREAD

**Issue by iamwill123** [mirjSolution/ChatTime#1]
https://github.com/mirjSolution/ChatTime/blob/369c5f1dcac6dbd56232307393cb09a8f4d4623b/components/Chat.js#L18

Hey for these credentials you should definitely put them in a `.env` file so that they're not public. It's not safe and easily hackable.

https://docs.expo.io/guides/environment-variables/

**Comment by mirjSolution** [comment]
Hey Will, Thank you i just move my firebase token to .env
